import Link from "next/link";
import { ArrowUpRight, Mail, MapPin } from "lucide-react";
import { Logo } from "./header";
const columns = [
  {title:"Banking", links:[["Co-operative Banks","/banking/co-operative-banks"],["Urban Co-operative Banks","/banking/urban-co-operative-banks"],["Credit Co-operative Societies","/banking/credit-co-operative-societies"],["Digital Banking","/banking/digital-banking"],["Collection Infrastructure","/banking/collection-infrastructure"]]},
  {title:"Solutions", links:[["UPI AutoPay","/solutions/upi-autopay"],["Virtual Accounts","/solutions/virtual-accounts"],["UPI QR","/solutions/upi-qr"],["POS Machines","/solutions/pos"],["Micro ATM","/solutions/micro-atm"]]},
  {title:"Industries & Company", links:[["Housing Societies","/industries/housing-societies"],["Education","/industries/education"],["Healthcare","/industries/healthcare"],["About us","/about"],["Why Mahacred","/why-mahacred"]]},
  {title:"Resources & Legal", links:[["Technology & Security","/technology-security"],["FAQs","/faqs"],["Grievance / Support","/support"],["Privacy Policy","/legal/privacy"],["Terms & Conditions","/legal/terms"]]},
];
export function Footer(){return <footer><div className="footer-main container"><div className="footer-brand"><Logo/><p>Powering Digital Payments.<br/>Simplifying Collections.</p><a href="mailto:business@mahacred.in"><Mail size={16}/> business@mahacred.in</a><span><MapPin size={16}/> India</span></div>{columns.map(c=><div className="footer-col" key={c.title}><h3>{c.title}</h3>{c.links.map(([l,h])=><Link key={h} href={h}>{l}<ArrowUpRight size={12}/></Link>)}</div>)}</div><div className="footer-legal container"><p>© 2026 Mahacred Firstpaytech. All Rights Reserved.</p><div><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link><Link href="/legal/disclaimer">Disclaimer</Link><Link href="/support">Grievance / Support</Link></div></div><p className="disclaimer container">Services and availability are subject to applicable eligibility, banking, payment-network, partner and regulatory requirements. Mahacred Firstpaytech provides technology solutions and does not represent itself as a bank.</p></footer>}
