import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Building2, Check, Landmark, Network, QrCode, RefreshCw, ShieldCheck, Store, WalletCards } from "lucide-react";
import { CTA, Ecosystem, SectionTitle } from "./ui";

const products=[
 {n:"01",title:"UPI AutoPay",copy:"Mandate-led recurring collections with clear payment status.",href:"/solutions/upi-autopay",kind:"timeline"},
 {n:"02",title:"Virtual Accounts",copy:"Unique references that bring structure to identification and reconciliation.",href:"/solutions/virtual-accounts",kind:"reconcile"},
 {n:"03",title:"QR Acceptance",copy:"Static and dynamic UPI QR experiences for merchants and counters.",href:"/solutions/upi-qr",kind:"qr"},
 {n:"04",title:"POS & Merchant Payments",copy:"Card acceptance and payment infrastructure for eligible businesses.",href:"/solutions/pos",kind:"pos"},
 {n:"05",title:"Micro ATM",copy:"Assisted transaction touchpoints for eligible service models.",href:"/solutions/micro-atm",kind:"assist"},
 {n:"06",title:"Collection Infrastructure",copy:"Multi-channel flows connected to operational reconciliation.",href:"/banking/collection-infrastructure",kind:"collect"},
];
const industries=[["Co-operative Banking","/banking/co-operative-banks","/images/banking-team.jpg"],["Housing Societies","/industries/housing-societies","/images/housing.jpg"],["Retail & Merchants","/industries/retail-merchants","/images/merchant-pos.jpg"],["Enterprise & Institutions","/industries","/images/enterprise.jpg"]];

export function HomePage(){return <>
 <section className="hero hero-v2"><div className="hero-grid-lines"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><i/> Banking Technology · Digital Payments · Collections</span><h1>Empowering Co-operative Banks with Modern <em>Digital Payment Technology</em></h1><p>Mahacred Firstpaytech delivers technology-driven payment, collection and merchant enablement solutions designed for Co-operative Banks, financial institutions and modern businesses.</p><div className="hero-actions"><Link className="button primary" href="/banking/co-operative-banks">Explore Banking Solutions <ArrowRight size={18}/></Link><Link className="button ghost" href="/contact">Talk to Our Team</Link></div><div className="hero-proof"><span><ShieldCheck/>Security-conscious</span><span><Network/>Integration-ready</span><span><Landmark/>Banking-focused</span></div></div>
 <div className="hero-photo-composition"><div className="hero-photo"><Image src="/images/banking-team.jpg" alt="Professionals collaborating in a modern banking environment" fill priority loading="eager" sizes="(max-width: 768px) 100vw, 48vw"/></div><div className="transaction-float"><div><span className="pulse"/><small>PAYMENT INFRASTRUCTURE</small></div><strong>Connected and status-aware</strong><div className="mini-chart"><i/><i/><i/><i/><i/></div></div><div className="solution-float"><span>CO-OPERATIVE BANKING</span><b>Technology Layer</b>{["UPI AutoPay","Virtual Accounts","UPI QR","POS","Collections"].map(x=><small key={x}>{x}<Check size={11}/></small>)}</div></div></div></section>
 <section className="institution-bar"><div className="container"><span>Focused on the co-operative banking ecosystem</span><p>Technology designed around financial workflows, customer experience and operational clarity.</p></div></section>

 <section className="section coop-editorial"><div className="container"><div className="editorial-grid"><div className="editorial-image"><Image src="/images/banking-team.jpg" alt="Banking professionals in a strategic meeting" fill sizes="(max-width: 768px) 100vw, 45vw"/><div className="image-caption"><span>PRIMARY FOCUS</span><b>Co-operative Banking</b></div></div><div className="editorial-copy"><SectionTitle eyebrow="Built for co-operative banking" title="Technology Built Around Co-operative Banking" copy="Modern payment capabilities are most useful when they fit the institution, its customers and the communities it serves."/><p>Mahacred connects collection, merchant acceptance and assisted-payment possibilities through a practical technology layer—giving bank teams a clearer way to shape digital experiences.</p><Link className="text-link" href="/banking/co-operative-banks">Explore our banking approach <ArrowRight size={17}/></Link></div></div>
 <div className="infra-map"><div className="infra-source"><Landmark/><small>INSTITUTION</small><b>Co-operative Bank</b></div><div className="infra-line"><i/><span>MAHACRED<br/><small>TECHNOLOGY LAYER</small></span><i/></div><div className="infra-products">{[[RefreshCw,"UPI AutoPay"],[WalletCards,"Virtual Accounts"],[QrCode,"Merchant QR"],[Store,"POS"],[Building2,"Micro ATM"],[Network,"Collections"]].map(([Icon,label])=><div key={label as string}><Icon size={20}/><span>{label as string}</span></div>)}</div><div className="infra-audiences"><span>Customers</span><span>Merchants</span><span>Institutions</span><span>Housing Societies</span></div></div></div></section>

 <section className="section product-editorial"><div className="container"><SectionTitle eyebrow="Connected payment capabilities" title="Infrastructure for every collection moment" copy="Distinct capabilities, brought together around the institution’s operating model."/><div className="product-rows">{products.map(p=><Link href={p.href} className={`product-row ${p.kind}`} key={p.title}><span className="product-num">{p.n}</span><div><h3>{p.title}</h3><p>{p.copy}</p></div><div className="product-visual">{p.kind==="timeline"&&<><i/><i/><i/><i/></>}{p.kind==="reconcile"&&<><b>REF–2048</b><span>MATCHED</span></>}{p.kind==="qr"&&<QrCode/>}{p.kind==="pos"&&<Store/>}{p.kind==="assist"&&<Building2/>}{p.kind==="collect"&&<Network/>}</div><ArrowRight className="row-arrow"/></Link>)}</div></div></section>

 <section className="section autopay-showcase"><div className="container split"><div><SectionTitle light eyebrow="UPI AutoPay" title="A recurring collection journey with operational clarity" copy="From customer authorisation to payment status, every stage is considered as part of one connected workflow."/><ul className="tick-list"><li>Mandate-based customer experience</li><li>Schedule-aligned debit requests</li><li>Payment status visibility</li><li>Structured reconciliation</li></ul><Link className="text-link" href="/solutions/upi-autopay">Explore UPI AutoPay <ArrowRight size={17}/></Link></div><div className="autopay-console"><div className="console-head"><span>RECURRING COLLECTION FLOW</span><i>READY</i></div>{["Customer","Mandate Authorisation","Scheduled Collection","Payment Processing","Status / Reconciliation"].map((x,i)=><div className="console-step" key={x}><span>{String(i+1).padStart(2,"0")}</span><i/><b>{x}</b><small>{i<4?"NEXT":"COMPLETE"}</small></div>)}<p>Payment outcomes remain subject to customer, account, network and partner conditions.</p></div></div></section>

 <section className="society-feature"><div className="society-bg"><Image src="/images/housing.jpg" alt="Modern residential community representing housing society collections" fill sizes="100vw"/></div><div className="container society-content"><span className="eyebrow">HOUSING SOCIETY COLLECTIONS</span><h2>Smarter Maintenance Collections for Modern Housing Societies</h2><p>A structured recurring-payment experience connecting co-operative banks, society teams and residents.</p><div className="stakeholder-columns"><div><small>FOR CO-OPERATIVE BANKS</small><b>Deepen society engagement</b><p>Enable a relevant institutional collection ecosystem.</p></div><div><small>FOR HOUSING SOCIETIES</small><b>Reduce monthly effort</b><p>Improve tracking and reconciliation structure.</p></div><div><small>FOR RESIDENTS</small><b>Pay with less repetition</b><p>Use a convenient UPI mandate experience.</p></div></div><Ecosystem type="society"/><Link className="button white" href="/solutions/housing-society-collections">Explore society collections <ArrowRight size={17}/></Link></div></section>

 <section className="section merchant-feature"><div className="container editorial-grid reverse"><div className="editorial-copy"><SectionTitle eyebrow="Merchant payment ecosystem" title="Acceptance infrastructure for real business environments" copy="Enable payment experiences across local merchants, multi-location businesses, healthcare, hospitality and institutional counters."/><div className="editorial-list"><span><b>01</b> QR-based acceptance</span><span><b>02</b> POS and card acceptance</span><span><b>03</b> Merchant network enablement</span></div><Link className="button dark" href="/solutions/merchant-payments">Explore merchant payments <ArrowRight size={17}/></Link></div><div className="editorial-image merchant-image"><Image src="/images/merchant-pos.jpg" alt="Merchant payment acceptance at a business counter" fill sizes="(max-width: 768px) 100vw, 45vw"/><div className="image-caption"><span>PAYMENT ACCEPTANCE</span><b>Connected merchant experiences</b></div></div></div></section>

 <section className="section trust-editorial"><div className="container trust-layout"><div><SectionTitle eyebrow="Technology & trust" title="Built for Trust. Designed for Financial Workflows." copy="Confidence comes from considered architecture, clear implementation and responsible operating boundaries—not unverified claims."/><Link className="text-link" href="/technology-security">Our technology approach <ArrowRight size={17}/></Link></div><div className="trust-lines">{["Security-conscious architecture","Structured onboarding","Integration-ready technology","Scalable infrastructure","Business-focused implementation","Compliance-conscious processes"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ShieldCheck size={18}/></div>)}</div></div></section>

 <section className="section industries-visual"><div className="container"><SectionTitle eyebrow="Industries" title="Payment technology in its operating context"/><div className="industry-tiles">{industries.map(([x,h,img],i)=><Link href={h} key={x} className={i===0?"wide":""}><Image src={img} alt={`${x} environment`} fill sizes="(max-width:768px) 100vw, 50vw"/><span>0{i+1}</span><div><h3>{x}</h3><p>Explore solutions <ArrowRight size={15}/></p></div></Link>)}</div></div></section>

 <section className="section why-editorial"><div className="container trust-layout"><div><span className="eyebrow">WHY MAHACRED</span><h2>One Technology Partner. Multiple Payment Capabilities.</h2><p>Banking context and payment infrastructure, considered as one connected institutional opportunity.</p></div><div className="trust-lines">{["Banking-focused approach","Payment infrastructure","Collection automation","Merchant enablement","Scalable integration","Institutional support"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ArrowRight size={18}/></div>)}</div></div></section>
 <CTA title="Ready to Modernise Your Payment & Collection Infrastructure?" copy="Talk to our team about banking, recurring collection and merchant payment requirements."/>
 </>}
