import Link from "next/link";
import { ArrowRight, CheckCircle2, Layers3, Network, ShieldCheck, Sparkles } from "lucide-react";
import { CapabilityGrid, CTA, Ecosystem, SectionTitle } from "./ui";
const banks=[{n:"01",t:"Digital payment enablement",c:"Modern customer and institutional payment journeys."},{n:"02",t:"Merchant network enablement",c:"Acceptance infrastructure for local business ecosystems."},{n:"03",t:"Collection infrastructure",c:"Structured identification, status and reconciliation."},{n:"04",t:"Assisted touchpoints",c:"Eligible service models that extend local access."}];
export function HomePage(){return <>
 <section className="hero"><div className="hero-orb"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><i/> Banking technology for institutional India</span><h1>Empowering Co-operative Banks with Modern <em>Digital Payment Technology.</em></h1><p>Mahacred Firstpaytech delivers technology-driven payment, collection and merchant enablement solutions designed for Co-operative Banks, financial institutions and modern businesses.</p><div className="hero-actions"><Link className="button primary" href="/banking/co-operative-banks">Explore Banking Solutions <ArrowRight size={18}/></Link><Link className="button ghost" href="/contact">Talk to Our Team</Link></div><div className="hero-proof"><span><ShieldCheck/>Security-conscious</span><span><Network/>Integration-ready</span><span><Layers3/>Built to scale</span></div></div><div className="hero-visual"><div className="visual-top"><span>PAYMENT ECOSYSTEM</span><i>LIVE ARCHITECTURE</i></div><div className="bank-chip"><div><Sparkles/><small>INSTITUTION</small><b>Co-operative Bank</b></div><span>CONNECTED</span></div><div className="connector"><i/><b>MAHACRED FIRSTPAYTECH</b><small>TECHNOLOGY LAYER</small><i/></div><div className="product-nodes"><span>UPI AutoPay</span><span>Virtual Accounts</span><span>UPI QR</span><span>POS</span><span>Micro ATM</span><span>Collections</span></div><div className="visual-foot"><span>Customers</span><i/><span>Merchants</span><i/><span>Institutions</span></div></div></div></section>
 <section className="trust-strip"><div className="container"><p>Technology designed for</p><span>CO-OPERATIVE BANKS</span><i/><span>FINANCIAL INSTITUTIONS</span><i/><span>MODERN ENTERPRISES</span></div></section>
 <section className="section light"><div className="container"><SectionTitle eyebrow="Our defining focus" title="Built for Co-operative Banking" copy="Technology that respects the distinct relationships, workflows and opportunities within the co-operative ecosystem."/><div className="bank-focus"><div className="focus-intro"><span>LOCAL ROOTS.<br/>MODERN RAILS.</span><p>Help your institution build a more connected digital proposition across customers, merchants, housing societies and community businesses.</p><Link href="/banking/co-operative-banks">Explore the banking opportunity <ArrowRight size={16}/></Link></div><div className="focus-list">{banks.map(x=><div key={x.n}><span>{x.n}</span><h3>{x.t}</h3><p>{x.c}</p></div>)}</div></div></div></section>
 <section className="section ink"><div className="container"><SectionTitle light eyebrow="Connected capabilities" title="One technology partner. Multiple solutions." copy="Build an ecosystem—not a collection of disconnected products."/><Ecosystem/><div className="mini-features"><span><CheckCircle2/>Payment acceptance</span><span><CheckCircle2/>Recurring collections</span><span><CheckCircle2/>Reconciliation</span><span><CheckCircle2/>Merchant enablement</span></div></div></section>
 <section className="section"><div className="container"><SectionTitle eyebrow="Payment solutions" title="Infrastructure for every collection moment" copy="Modular capabilities, thoughtfully connected to institutional and commercial use cases."/><CapabilityGrid/></div></section>
 <section className="section blue-feature"><div className="container split"><div><SectionTitle light eyebrow="UPI AutoPay" title="Make recurring collections feel effortless" copy="Create a mandate-based journey for maintenance, EMIs, fees, subscriptions and other periodic payments."/><ul className="tick-list"><li>Customer-friendly mandate experience</li><li>Schedule-aligned debit requests</li><li>Payment status visibility</li><li>Structured operational follow-up</li></ul><Link className="text-link" href="/solutions/upi-autopay">Explore UPI AutoPay <ArrowRight size={17}/></Link></div><Ecosystem type="autopay"/></div></section>
 <section className="section society"><div className="container"><SectionTitle eyebrow="Housing society collections" title="A better maintenance cycle—for everyone" copy="Connect banks, societies and residents through a clear recurring payment experience."/><Ecosystem type="society"/><div className="audience-grid"><div><small>FOR BANKS</small><h3>Strengthen society relationships</h3><p>Build digital engagement around a relevant institutional use case.</p></div><div><small>FOR SOCIETIES</small><h3>Reduce monthly collection effort</h3><p>Improve tracking and structure reconciliation.</p></div><div><small>FOR RESIDENTS</small><h3>Pay with less repetition</h3><p>Use a convenient UPI-based mandate journey.</p></div></div></div></section>
 <section className="section"><div className="container split reverse"><Ecosystem type="virtual"/><div><SectionTitle eyebrow="Virtual Accounts" title="Know who paid—without the guesswork" copy="Connect incoming payments to unique customer, invoice or business references for more structured reconciliation."/><ul className="plain-list"><li>Customer-wise collections</li><li>Dealer and distributor networks</li><li>Education and enterprise receivables</li><li>Housing society collections</li></ul><Link className="button dark" href="/solutions/virtual-accounts">Explore Virtual Accounts <ArrowRight size={17}/></Link></div></div></section>
 <section className="section soft"><div className="container"><SectionTitle eyebrow="Industries" title="Designed for the way your sector works"/><div className="industry-row">{[["Co-operative Banking","/banking/co-operative-banks"],["Housing Societies","/industries/housing-societies"],["Education","/industries/education"],["Healthcare","/industries/healthcare"],["Retail & Merchants","/industries/retail-merchants"],["Financial Institutions","/industries/financial-institutions"]].map(([x,h],i)=><Link href={h} key={x}><span>0{i+1}</span><b>{x}</b><ArrowRight/></Link>)}</div></div></section>
 <section className="section"><div className="container security"><div><SectionTitle eyebrow="Technology & Security" title="Designed around banking requirements" copy="A considered foundation for integration, operational visibility and responsible growth."/><Link className="text-link" href="/technology-security">Our technology approach <ArrowRight size={17}/></Link></div><div className="security-grid">{[["Security-conscious architecture","Data and access considered across the journey."],["Integration-ready approach","Interfaces designed around relevant workflows."],["Structured onboarding","Clear stages from discovery to rollout."],["Business-focused support","Context-aware support for operating teams."]].map(([t,c])=><div key={t}><ShieldCheck/><h3>{t}</h3><p>{c}</p></div>)}</div></div></section><CTA/>
 </>}
