import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, CreditCard, Landmark, Network, QrCode, ShieldCheck, Smartphone, WalletCards } from "lucide-react";
import { CTA, Ecosystem, SectionTitle } from "./ui";

const solutions=[
 {title:"UPI AutoPay",copy:"Mandate-based recurring collection experiences.",href:"/solutions/upi-autopay",type:"autopay"},
 {title:"Virtual Accounts",copy:"Identifiable references for structured reconciliation.",href:"/solutions/virtual-accounts",type:"virtual"},
 {title:"UPI QR",copy:"Illustrative QR acceptance for merchants and counters.",href:"/solutions/upi-qr",type:"qr"},
 {title:"Dynamic QR",copy:"Transaction-linked QR with amount and payment context.",href:"/solutions/dynamic-qr",type:"dynamic"},
 {title:"POS / Swipe Machines",copy:"Card and contactless acceptance where supported.",href:"/solutions/pos",type:"pos"},
 {title:"Micro ATM",copy:"Assisted touchpoints for eligible service models.",href:"/solutions/micro-atm",type:"micro"},
 {title:"Collection Solutions",copy:"Multi-channel payment visibility and reconciliation.",href:"/banking/collection-infrastructure",type:"collection"},
];
const industries=[["Co-operative Banks","/banking/co-operative-banks","/images/banking-team.jpg"],["Credit Co-operative Societies","/banking/credit-co-operative-societies","/images/industry-team.jpg"],["Housing Societies","/industries/housing-societies","/images/housing.jpg"],["Retail & Merchants","/industries/retail-merchants","/images/merchant-pos.jpg"],["Enterprises & Institutions","/industries","/images/enterprise.jpg"]];

function ProductVisual({type}:{type:string}){if(type==="autopay")return <div className="pv phone"><Smartphone/><span>MANDATE ACTIVE</span><b>Monthly collection</b><small><CalendarDays/> Scheduled</small></div>;if(type==="virtual")return <div className="pv account"><small>VIRTUAL ACCOUNT</small><b>91•• •••• 4821</b><i>PAYMENT IDENTIFIED</i></div>;if(type==="qr")return <div className="pv qr"><QrCode/><span>Merchant payment</span></div>;if(type==="dynamic")return <div className="pv dynamic"><b>₹ 2,450</b><ArrowRight/><QrCode/></div>;if(type==="pos")return <div className="pv pos"><CreditCard/><span>TAP / INSERT</span><b>₹ 1,280</b></div>;if(type==="micro")return <div className="pv micro"><Smartphone/><span>ASSISTED TOUCHPOINT</span><i/></div>;return <div className="pv collect"><span>UPI</span><span>VA</span><span>QR</span><Network/><b>RECONCILED</b></div>}

export function HomePage(){return <>
 <section className="hero indigo-hero"><div className="indigo-grid"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><i/> Banking Technology · Digital Payments · Collections</span><h1>Empowering Co-operative Banks & Credit Societies with Modern <em>Digital Payment Technology</em></h1><p>Mahacred Firstpaytech delivers modern payment, recurring collection and merchant enablement solutions for Co-operative Banks, Credit Co-operative Societies, financial institutions, merchants and communities.</p><div className="hero-actions"><Link className="button primary" href="/banking/co-operative-banks">Explore Banking Solutions <ArrowRight size={18}/></Link><Link className="button ghost" href="/contact">Talk to Our Team</Link></div><div className="hero-proof"><span><ShieldCheck/>Security-conscious</span><span><Network/>Integration-ready</span><span><Landmark/>Banking-focused</span></div></div>
 <div className="ecosystem-orbit"><div className="orbit-glow"/><div className="orbit-core"><Landmark/><small>INSTITUTION</small><b>Bank / Credit Society</b><span>MAHACRED TECHNOLOGY</span></div><div className="orbit-node n1"><Smartphone/><b>UPI AutoPay</b><small>Mandate active</small></div><div className="orbit-node n2"><WalletCards/><b>Virtual Account</b><small>Payment matched</small></div><div className="orbit-node n3"><QrCode/><b>UPI QR</b><small>Illustrative scan</small></div><div className="orbit-node n4"><CreditCard/><b>POS</b><small>Tap / insert</small></div><div className="orbit-node n5"><Smartphone/><b>Micro ATM</b><small>Assisted access</small></div><div className="orbit-node n6"><Network/><b>Collections</b><small>Reconciled</small></div></div></div></section>
 <section className="position-strip"><div className="container"><span>Designed for institutional financial workflows</span><p>Co-operative Banks</p><i/><p>Credit Co-operative Societies</p><i/><p>Financial Institutions</p></div></section>

 <section className="section dual-focus"><div className="container"><SectionTitle eyebrow="Primary institutional focus" title="Technology Designed for Co-operative Banks & Credit Societies" copy="Two distinct operating contexts, supported through connected payment and collection capabilities."/><div className="focus-panels"><article><div className="panel-image"><Image src="/images/banking-team.jpg" alt="Professional co-operative banking discussion" fill sizes="(max-width:768px) 100vw, 50vw"/></div><span>CO-OPERATIVE BANKS</span><h3>Extend modern payment experiences across customers and local ecosystems.</h3><ul><li>UPI AutoPay</li><li>Virtual Accounts</li><li>QR & POS</li><li>Micro ATM</li><li>Collections</li></ul><Link href="/banking/co-operative-banks">Explore Co-operative Banking <ArrowRight/></Link></article><article><div className="panel-image"><Image src="/images/industry-team.jpg" alt="Credit society and member-service professionals" fill sizes="(max-width:768px) 100vw, 50vw"/></div><span>CREDIT CO-OPERATIVE SOCIETIES</span><h3>Structure eligible member, recurring and branch-level payment journeys.</h3><ul><li>Recurring collections</li><li>Member payments</li><li>EMI collections</li><li>Virtual Accounts</li><li>QR & POS</li></ul><Link href="/banking/credit-co-operative-societies">Explore Credit Society Solutions <ArrowRight/></Link></article></div></div></section>

 <section className="section solution-showcase"><div className="container"><SectionTitle eyebrow="Our capabilities" title="Our Payment & Collection Solutions" copy="Product experiences that look clear to customers and remain useful to institutional operating teams."/><div className="visual-product-grid">{solutions.map((s,i)=><Link href={s.href} className={`visual-product ${s.type} ${i===0||i===6?"wide":""}`} key={s.title}><div className="product-stage"><ProductVisual type={s.type}/></div><small>0{i+1}</small><h3>{s.title}</h3><p>{s.copy}</p><span>Explore <ArrowRight/></span></Link>)}</div></div></section>

 <section className="section institutional-types"><div className="container"><div><span className="eyebrow">INSTITUTIONS WE DESIGN FOR</span><h2>Co-operative finance has many operating models.</h2><p>Our technology approach can be shaped for eligible institutions and use cases without implying a client relationship.</p></div><div>{["Urban Co-operative Banks","Credit Co-operative Societies","District Central Co-operative Banks","Multi-State Co-operative Banks","Other eligible Co-operative Financial Institutions"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ArrowRight/></div>)}</div></div></section>

 <section className="section autopay-showcase violet-dark"><div className="container split"><div><SectionTitle light eyebrow="UPI AutoPay" title="Recurring collections, presented as one clear journey" copy="A mandate-based experience for eligible recurring payments, supported by schedule and status visibility."/><ul className="tick-list"><li>Customer mandate authorisation</li><li>Schedule-aligned collection request</li><li>Payment processing status</li><li>Reconciliation-ready output</li></ul><Link className="text-link" href="/solutions/upi-autopay">Explore UPI AutoPay <ArrowRight/></Link></div><div className="mandate-device"><div className="device-top"><span>UPI MANDATE</span><i>ACTIVE</i></div><b>Recurring collection</b><strong>₹ 2,500</strong><small>Monthly · Scheduled</small><div className="schedule-bars"><i/><i/><i/><i/></div><p><Check/> Mandate authorised</p><p><CalendarDays/> Next request scheduled</p></div></div></section>

 <section className="society-feature"><div className="society-bg"><Image src="/images/housing.jpg" alt="Modern residential community" fill sizes="100vw"/></div><div className="container society-content"><span className="eyebrow">HOUSING SOCIETY COLLECTIONS</span><h2>Smarter Maintenance Collections for Modern Housing Societies</h2><p>A structured recurring-payment journey connecting co-operative banks, society teams and residents.</p><div className="stakeholder-columns"><div><small>FOR CO-OPERATIVE BANKS</small><b>Deepen society engagement</b></div><div><small>FOR HOUSING SOCIETIES</small><b>Reduce monthly effort</b></div><div><small>FOR RESIDENTS</small><b>Pay with less repetition</b></div></div><Ecosystem type="society"/><Link className="button white" href="/solutions/housing-society-collections">Explore society collections <ArrowRight/></Link></div></section>

 <section className="section trust-editorial"><div className="container trust-layout"><div><SectionTitle eyebrow="Technology & trust" title="Built for Trust. Designed for Financial Workflows." copy="Confidence comes from considered architecture, clear implementation and responsible operating boundaries—not invented credentials."/><Link className="text-link" href="/technology-security">Our technology approach <ArrowRight/></Link></div><div className="trust-lines">{["Security-conscious architecture","Scalable infrastructure","Structured onboarding","Integration-ready technology","Banking-focused approach","Business support","Compliance-conscious processes"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><ShieldCheck/></div>)}</div></div></section>

 <section className="section industries-violet"><div className="container"><SectionTitle eyebrow="Industries" title="Technology in its operating context"/><div className="industry-cascade">{industries.map(([x,h,img],i)=><Link href={h} key={x}><Image src={img} alt={`${x} professional environment`} fill sizes="(max-width:768px) 100vw, 33vw"/><span>0{i+1}</span><h3>{x}</h3><p>Explore solutions <ArrowRight/></p></Link>)}</div></div></section>

 <section className="section process-section"><div className="container"><SectionTitle light eyebrow="Implementation approach" title="From institutional use case to operational readiness"/><div className="process-line">{[["01","Discover"],["02","Design"],["03","Validate"],["04","Enable"]].map(([n,t])=><div key={n}><span>{n}</span><i/><h3>{t}</h3><p>Align the relevant stakeholders, workflows and readiness requirements.</p></div>)}</div></div></section>
 <CTA title="Ready to Modernise Your Payment & Collection Infrastructure?" copy="Talk to our team about banking, credit society, recurring collection and merchant payment requirements."/>
 </>}
