import Link from "next/link";
import { ArrowRight, Check, Building2, Landmark, QrCode, RefreshCw, ShieldCheck, Store, WalletCards } from "lucide-react";
export function SectionTitle({eyebrow,title,copy,light=false}:{eyebrow:string;title:string;copy?:string;light?:boolean}){return <div className={`section-title ${light?"light":""}`}><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
export function CTA({title="Build your next payment experience with us",copy="Let’s map the right solution for your institution, customers and operating model."}:{title?:string;copy?:string}){return <section className="cta-wrap"><div className="cta-card container"><div><span className="eyebrow">A focused technology conversation</span><h2>{title}</h2><p>{copy}</p></div><Link className="button white" href="/contact">Talk to our team <ArrowRight size={18}/></Link></div></section>}
export function Ecosystem({type="bank"}:{type?:"bank"|"autopay"|"virtual"|"society"}){
 const maps={bank:[["Co-operative Bank",Landmark],["Mahacred Technology Layer",ShieldCheck],["Payments & Collections",WalletCards],["Customers & Merchants",Store]],autopay:[["Customer",Building2],["UPI Mandate",Check],["Scheduled Request",RefreshCw],["Payment Status",WalletCards]],virtual:[["Customer",Building2],["Unique Virtual Account",WalletCards],["Identification",Check],["Reconciliation",RefreshCw]],society:[["Resident",Building2],["UPI Mandate",Check],["Scheduled Maintenance",RefreshCw],["Payment Status",WalletCards],["Reconciliation",Check]]};
 return <div className={`ecosystem ${type}`}>{maps[type].map(([label,Icon],i,steps)=><div className="flow-step" key={label as string}><span>{String(i+1).padStart(2,"0")}</span><Icon size={22}/><b>{label as string}</b>{i<steps.length-1&&<i><ArrowRight size={16}/></i>}</div>)}</div>
}
export const capabilities=[{icon:RefreshCw,title:"UPI AutoPay",copy:"Mandate-based recurring collection journeys.",href:"/solutions/upi-autopay"},{icon:WalletCards,title:"Virtual Accounts",copy:"Unique references for structured reconciliation.",href:"/solutions/virtual-accounts"},{icon:QrCode,title:"UPI QR",copy:"Acceptance for merchants, branches and counters.",href:"/solutions/upi-qr"},{icon:Store,title:"POS Acceptance",copy:"Card payment options for eligible merchants.",href:"/solutions/pos"},{icon:Landmark,title:"Banking Solutions",copy:"Connected infrastructure for co-operative banks.",href:"/banking/co-operative-banks"},{icon:Building2,title:"Society Collections",copy:"A better maintenance collection experience.",href:"/solutions/housing-society-collections"}];
export function CapabilityGrid(){return <div className="cap-grid">{capabilities.map(c=><Link className="cap-card" href={c.href} key={c.title}><span><c.icon size={22}/></span><h3>{c.title}</h3><p>{c.copy}</p><b>Explore solution <ArrowRight size={15}/></b></Link>)}</div>}
